import uuid

from rag_engine.domain.base import NoSQLBaseDocument


class _Doc(NoSQLBaseDocument):
    name: str = "example"


def test_id_is_autogenerated_uuid():
    doc = _Doc()

    assert isinstance(doc.id, uuid.UUID)


def test_each_instance_gets_a_distinct_id():
    assert _Doc().id != _Doc().id


def test_equality_and_hash_by_id():
    shared_id = uuid.uuid4()
    a = _Doc(id=shared_id, name="a")
    b = _Doc(id=shared_id, name="b")

    assert a == b
    assert hash(a) == hash(b)


def test_documents_with_different_ids_are_not_equal():
    assert _Doc() != _Doc()


def test_instances_are_hashable_and_usable_in_a_set():
    shared_id = uuid.uuid4()
    a = _Doc(id=shared_id)
    b = _Doc(id=shared_id)

    assert len({a, b}) == 1
