import uuid

import pytest
from pydantic import Field

from rag_engine.domain.base import NoSQLBaseDocument


# --------------------------------------------------------------------------- #
# Helpers — concrete subclasses under test (underscore-prefixed so pytest does
# not collect them as test classes).
# --------------------------------------------------------------------------- #
class _Doc(NoSQLBaseDocument):
    name: str = "example"


class _DocWithRef(NoSQLBaseDocument):
    ref_id: uuid.UUID = Field(default_factory=uuid.uuid4)


# --------------------------------------------------------------------------- #
# Tests
# --------------------------------------------------------------------------- #
class TestBaseClassSkeleton_70:
    """#70 — NoSQLBaseDocument skeleton: auto-generated id + identity semantics.

    A plain pytest class (NOT unittest.TestCase); methods use bare asserts.
    """

    def test_id_is_autogenerated_uuid(self):
        doc = _Doc()

        assert isinstance(doc.id, uuid.UUID)

    def test_each_instance_gets_a_distinct_id(self):
        assert _Doc().id != _Doc().id

    def test_equality_and_hash_by_id(self):
        # Two documents sharing an id are the same identity, regardless of payload.
        shared_id = uuid.uuid4()
        a = _Doc(id=shared_id, name="a")
        b = _Doc(id=shared_id, name="b")

        assert a == b
        assert hash(a) == hash(b)

    def test_documents_with_different_ids_are_not_equal(self):
        assert _Doc() != _Doc()

    def test_instances_are_hashable_and_usable_in_a_set(self):
        shared_id = uuid.uuid4()
        a = _Doc(id=shared_id)
        b = _Doc(id=shared_id)

        assert len({a, b}) == 1


class TestModelSerialization_71:
    """#71 — Mongo <-> model serialization via to_mongo / from_mongo."""

    def test_to_mongo_maps_id_to_stringified_underscore_id(self):
        # Act
        data = _Doc().to_mongo()

        # Assert — id is emitted under the "_id" alias as a string.
        assert "_id" in data
        assert "id" not in data
        assert isinstance(data["_id"], str)

    def test_from_mongo_round_trip_reproduces_the_model(self):
        # Arrange
        doc = _Doc(name="hello")

        # Act
        restored = _Doc.from_mongo(doc.to_mongo())

        # Assert
        assert restored == doc
        assert restored.id == doc.id
        assert restored.name == doc.name

    def test_uuid_fields_are_stringified_and_restored(self):
        # Arrange
        doc = _DocWithRef()

        # Act
        data = doc.to_mongo()
        restored = _DocWithRef.from_mongo(data)

        # Assert — UUID -> str on the way out, str -> UUID on the way back.
        assert isinstance(data["ref_id"], str)
        assert isinstance(restored.ref_id, uuid.UUID)
        assert restored.ref_id == doc.ref_id

    def test_from_mongo_rejects_empty_data(self):
        with pytest.raises(ValueError):
            _Doc.from_mongo({})
